code:
  - 'modules/**'
  - 'gradle/**'
  - 'build.gradle'
  - 'settings.gradle'
  - 'gradle.properties'
  - 'gradlew'
  - 'gradlew.bat'
  - 'buildSrc/**'
  - '.editorconfig'
  - '.gitattributes'
  - '.gitignore'
  - 'qodana.yaml'
  - 'jitpack.yml'
  - 'release-please-config.json'
  - '.github/workflows/**'
  - '.github/actions/**'
  - '.github/scripts/**'
  - '.github/dependabot.yml'
  - '.github/code-paths-filter.yml'
