#!/usr/bin/env bash

set -euo pipefail

file_path=$(python3 -c 'import json, sys; print(json.load(sys.stdin).get("tool_input", {}).get("file_path", ""))')

[[ ${file_path##*/} == CHANGELOG.md ]] || exit 0

printf '%s\n' 'CHANGELOG.md is generated by release-please — never hand-edit it. Wrong entries are fixed by correcting the squash-merge commit subject.' >&2
exit 2
