plugins {
    id 'groovy'
    alias(libs.plugins.kotlin.jvm)
}

repositories {
    mavenCentral()
}

kotlin {
    jvmToolchain(25)
}

dependencies {
    implementation gradleApi()
    testImplementation libs.kotest.assertions.core
    testImplementation libs.kotest.runner.junit5
    testImplementation gradleTestKit()
    testRuntimeOnly libs.junit.platform.launcher
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()
}
